version: '3'

services:

  mysql-server:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=hello@123
      - MYSQL_DATABASE=neudim
      - MYSQL_CHARSET=latin1
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql-data:
