version: '3'
services:
  mysql-server:
    image: mysql:8.0
    container_name: mysql-server
    ports:
      - "3307:3306"
    env_file:
      - env/docker.env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=$${DB_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3
  product-management-system:
    image: product-management-system
    container_name: product-management-system
    ports:
      - "8080:8080"
    command: ["--config-path", "/app/config.yaml"]
    env_file:
      - env/docker.env
    depends_on:
      - mysql-server
    volumes:
      - ./config.yaml:/app/config.yaml