version: '3'
services:  
 product-management-system:
    image: product-management-system
    container_name: product-management-system
    network_mode: "host"  
    command: ["--config-path", "/app/config.yaml"]
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - env/docker.env
  